### PR TITLE
fix: Improve UX by disabling placeholder text selection on CommandInput component

### PR DESCRIPTION
**Pull request by dubisdev**
Hi @HuakunShen and thank you for this amazing app!

I added a small fix to the input css to disable the selection of the placeholder text.

I havent been able to test it as I can't start the project on my local, but that should fix it.

image

BTW. I worked in something similar to this project here (@rokiiapp) Its a port of @cerebroapp to tauri. I am not currently maintaining it, but maybe I can do a rework of some of the extensions to make them work with kunkun.

I'll investigate the extensions API and maybe I open some PRs in the extensions repo.

### CODE REVIEW

**Comment by HuakunShen** [comment]
@dubisdev 
Thank you for your interest and support to this project!
I am so glad someone would be willing to contribute extensions, without a great extension ecosystem this project will not succeed.
We can discuss this on Discord. You can find me through the discord invite link in `README.md`.

To dev the app locally I guess you are missing a few environment variables I didn't include in the source code, I will add a detailed instruction today. I just didn't think that there will be people trying to dev this app.

And may I ask how did you manage to select the placeholder? I am on Mac and couldn't select the placeholder.

**Comment by dubisdev** [comment]
Hi

Just joined the discord :)

I selected the placeholder while trying to move the app window dragging from the top bar.

https://github.com/user-attachments/assets/a5850648-7ecb-4b98-bb02-06ba2f712147

I'll create some issues/requests that I think might improve the user experience :) also some requests about the extensions API

**Comment by HuakunShen** [comment]
@dubisdev Thanks! 
I see, to move the window, I made the bottom bar draggable.

**Review by HuakunShen — CHANGES_REQUESTED** [review]
Can you make it `select-none`? 
I tested this, when only setting `placeholder:select-none`, this is how it looks 
image

**Comment by HuakunShen** [comment]
@dubisdev I added an instruction for running this project locally https://github.com/kunkunsh/kunkun/blob/dev/CONTRIBUTING.md

**Comment by dubisdev** [comment]
Great! I'll take a look when I have some time and then I'll update the PR with the changes :)

**Comment by HuakunShen** [comment]
Implemented https://github.com/kunkunsh/kunkun/commit/5301e620ce205bc4332d1c439b9c92281e587552

**Pull request closed without merging**
